### ISSUE TITLE
[Add] 더미데이터 삽입

### ISSUE THREAD

**Issue by MARKGRAYSIRO** [SnoopClass/Siro_Student_IKEA#1]
---

## 💡 Issue

 UI 구현을 위한 더미데이터를 삽입합니다. 
개발중에 더미데이터가 더 필요해 보이면 todo리스트를 추가하도록 하겠습니다.

## 📝  todo
- [ ] 최근 본 제품에 들어갈 이미지 삽입하기
- [ ] 제품 찾아보기에 들어갈 제목 / 이미지 삽입하기
- [ ] 켐페인 칸에 들어갈 이미지 삽입하기
- [ ] 인기제품 칸에 들어갈 이미지 / 가격 / 크기 / 옵션 유무 추가하기

**Comment by EuniceNam** [comment]
시로도 화이팅이요!
